### ISSUE TITLE
Make it work with leiningen

### ISSUE THREAD

**Issue by RickMoynihan** [RickMoynihan/nrebl.middleware#1]
There is a `lein` branch which works towards this but doesn't yet work properly:

https://github.com/RickMoynihan/nrebl.middleware/tree/lein

Help wanted.

**Comment by RickMoynihan** [comment]
Stack trace I get with that branch currently is:

```
SEVERE: Unhandled REPL handler exception processing message {:id b1840c7a-f297-424b-9a8d-5eeb5611142b, :op clone}
java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'clojure.tools.nrepl.transport/Transport found for class: nrebl.middleware$wrap_rebl_sender$reify__16473
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at clojure.tools.nrepl.transport$eval610$fn__611$G__601__618.invoke(transport.clj:16)
	at clojure.tools.nrepl.middleware.session$register_session.invokeStatic(session.clj:144)
	at clojure.tools.nrepl.middleware.session$register_session.invoke(session.clj:137)
	at clojure.tools.nrepl.middleware.session$session$fn__1231.invoke(session.clj:188)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__880.invoke(middleware.clj:22)
	at nrebl.middleware$wrap_nrebl$fn__16477.invoke(middleware.clj:49)
	at nrepl.middleware$wrap_conj_descriptor$fn__16287.invoke(middleware.clj:22)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__1304.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
